version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: false
          node-version: '14'
      - run: node --version
      - node/install-packages:
          pkg-manager: npm
      
      - run:
          command: npm run test
          name: Run tests
workflows:
  test_my_app:
    jobs:
      - install-node-example
      